spring.application.name=aws
aws.accessKey=AKIAVVJ7QQ2PH3JSFI3U
aws.secretKey=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
aws.region=eu-north-1
aws.bucketName=rahulv12356
presign.expiry=15
max-file-size: 2MB
spring.datasource.url=jdbc:mysql://localhost:3306/zipkin?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081